### ISSUE TITLE
Results and Visualization

### ISSUE THREAD

**Issue by StoneLabs** [p3h3/benzinpreis-crawler#1]
Hi,

I'm curious about your results. Would you mind uploading them? Maybe the visualization which is (i assume) produced with visualize.py? Or perhaps add them to the readme.

Thanks
Stone

**Comment by p3h3** [comment]
Hi,
I've actually been thinking about rendering them once a day and publishing them on my website..
The visualisation is actually just some live plotting, an actual analysis is done in the auswertung.py using matplotlib. It's still really shitty though..

I will however grant you a small sneak peak:

![image](https://user-images.githubusercontent.com/19916557/110336486-323dfa80-8025-11eb-811d-60f8fbbabdde.png)

This is an analysis screenshot from a few days ago for the price of SuperE10 of a local gas Station.

y is the price's deviation from the day's average in percent
x is the time in seconds since 1 am of the day (I told you it was shitty)
all graphs of the same color represent the same day of the week according to the following scheme:
`color_lookup = [
    "red",
    "orange",
    "yellow",
    "greenyellow",
    "green",
    "cyan",
    "blue",
    "magenta"
]`
- monday is red, the rest is logical

To conclude: I need more data and a bit more time to wrap my head around matplotlib But I've seen the same results along multiple gas stations: 
If you want diesel, get it between17:45 and 19:15.
If you want E10, get it between 18:00 and19:00 or 22:00 and 00:00.

**Comment by StoneLabs** [comment]
Very nice work, thanks
